retitle/go-sdk

.idea/vcs.xml, v5/schemas.go
**Description**
Adding support for ClientVisibility within parties
**Related issues or context**
https://compass-tech.atlassian.net/browse/TJ-34147
=> [TJ-34147] Add support for clientVisibility on parties

v5/schemas.go
- Expose a Document's client visibility as `ClientVisibilityStatus`
=> Feat: [TJ-39372] Expose the Document's Client Visibility Status

v5/schemas.go
Adding extra field to SDK v5, for Client Document Type
=> TJ-39724 adding doc type to sdk v5

v6/properties_info.go, v6/schemas.go, v6/transaction_packages.go, v6/transactions.go
Modifying Folder schema to return the new data from the external_api, this will allow expanding PropertyInfo and TransactionPackage information related to the Folder
=> [TJ-41989] Modifying Folder schema to return the new data from the external_api

v6/schemas.go
SDK changes to allow expanding property_info in transaction_package resource
=> [TJ-41989] Allow expanding transaction_package related property_info

.idea/vcs.xml, v6/schemas.go
Adding new fields to Transaction documents and folders to allow mobile use them
=> [TJ-43183] Adding new fields to transaction documents response

v5/schemas.go, v6/schemas.go
Add deal id to sdk for transaction (create), to utilize on reconciler to add request deal id when creating transaction.
[QA: None]
https://compass-tech.atlassian.net/browse/TJ-47818
=> Minor: [TJ-47818] Add deal id to sdk for transaction (create)

v6/documents.go, v6/schemas.go
update the sdk for upload document new schema for E-sing
=> Tj 47782 document upload

v6/schemas.go, v6/signature_requests.go
- Add API to support `SetEsignFlowDocuments` in go-sdk 
- https://compass-tech.atlassian.net/browse/TJ-46090
- https://compass-tech.atlassian.net/browse/TJ-46091
=> [TM-Esign] Add API to support SetEsignFlowDocuments in go-sdk 

v6/schemas.go, v6/signature_requests.go
- Add GetEsignFlowDocuments API
- https://compass-tech.atlassian.net/browse/TJ-46084
- https://compass-tech.atlassian.net/browse/TJ-46082
=> [TJ-46082/TJ-46084] Add GetEsignFlowDocuments API

v6/schemas.go, v6/signature_requests.go
- Add SetEsignTabConfig API to go-sdk
=> [TJ-46115] Add SetEsignTabConfig API to go-sdk 

v6/schemas.go, v6/signature_requests.go
Adds Flow review endpoint (`POST /signature_requests/flow_review`)
=> minor: Add signature request flow review (POST)

v6/schemas.go, v6/signature_requests.go
- Add GetEsignTabConfig API in glide-sdk
=> [TJ-46109] Add GetEsignTabConfig API in glide-sdk

v6/schemas.go, v6/transaction_signature_requests.go
- Transferring over changes from https://github.com/UrbanCompass/compass-glide-devapp/pull/2590/
=> [TJ-49248] add changes for timeline enrichment

v6/schemas.go, v6/signature_requests.go
- Add SplitAnnotationText endpoint
- TJ-46121
=> [TJ-46121] Add SplitAnnotationText endpoint

v6/schemas.go
auto-generated sdk code, with support for SR activity context.
=> Support SR activity context

v6/schemas.go, v6/signature_requests.go
auto-generated sdk code, with support for setting SR flow recipients.
=> Support setting SR flow recipients

v6/schemas.go
- Add transaction documents expand to GetEsignFlowDocumentsRequest 
- TJ-50704
=> [TJ-50704] Add transaction documents expand to GetEsignFlowDocumentsRequest

v6/schemas.go, v6/signature_requests.go
auto-generated sdk code, with support for duplicating SRs.
=> Support duplicating SR

v6/schemas.go
- Add transaction documents expand to SignatureRequestTabConfigDetailResponse 
- TJ-51272
=> [TJ-51272] Add transaction documents expand to SignatureRequestTabConfigDetailResponse 

v6/schemas.go, v6/signature_requests.go
- Add VoidSignatureRequest API to go-sdk
- TJ-46195
=> [TJ-46195] Add VoidSignatureRequest API to go-sdk

v6/signature_requests.go
=> minor: Add `Resend` to `SignatureRequestsResource`

v6/schemas.go, v6/signature_requests.go
- Add Signature Request Archive API into go-sdk
- TJ-46200
- TJ-46201
=> [TJ-46201] Add Signature Request Archive API into go-sdk

v6/schemas.go, v6/signature_requests.go
- To support  returning `envelope_document_id` in the SignatureRequestDocument
- TJ-50698
=> [TJ-50698] To support  returning `envelope_document_id` in the SignatureRequestDocument

v6/schemas.go
auto-generated sdk code, with support for latest version id on SR document.
=> Support latest version id for SR document

v6/envelopes.go, v6/schemas.go
StartRevision and CancelRevision envelopes to external api 
https://compass-tech.atlassian.net/browse/TJ-46298
https://compass-tech.atlassian.net/browse/TJ-46300
Its compass-glide-devapp part https://github.com/UrbanCompass/compass-glide-devapp/pull/2877
=> Added StartRevision and CancelRevision envelopes to external api sdks

v6/schemas.go, v6/signature_requests.go
- Add FlowSendRevision API to support ReviseSignatureRequest
- TJ-46219
=> [TJ-46219] Add FlowSendRevision API to support ReviseSignatureRequest

v6/schemas.go
Related to
https://github.com/UrbanCompass/compass-glide-devapp/pull/2962
=> Added CreatePspdfkit to DocumentUploadSchema

v6/documents.go, v6/schemas.go
Related to https://github.com/UrbanCompass/compass-glide-devapp/pull/3045
=> Added DocumentDetails endpoint to Documents

v6/schemas.go
- Replace `LockedSignerKeys` with `LockedSignerKeysByTdvId` in `SignatureRequestTabConfigDetailResponse` 
- TJ-55118
=> [TJ-55118] Replace LockedSignerKeys with LockedSignerKeysByTdvId

v6/schemas.go
- Add FirstName and LastName into SignatureRequestRecipient
- TJ-54492
=> [TJ-54492] Add FirstName and LastName into SignatureRequestRecipient

v6/envelopes.go, v6/schemas.go
- Add envelope Void api
- Ticket TJ-56587
=> [TJ-56587] Add envelope Void api

v6/envelope_document.go, v6/envelope_recipient.go, v6/envelopes.go, v6/schemas.go, v6/step.go
Take 2 at adding activities, documents and certificate document
=> adding activities and docs

v6/envelopes.go, v6/schemas.go
=> [TJ-56588] Add envelop send revision api
